import {
  cloneSynthParameters,
  DEFAULT_SYNTH_PARAMETERS,
} from "@/audio/default-parameters";
import type { ProgramPreset } from "@/audio/types";

export const PROGRAM_PRESETS: ProgramPreset[] = [
  {
    name: "Init",
    parameters: cloneSynthParameters(DEFAULT_SYNTH_PARAMETERS),
  },
  {
    name: "Bass1",
    parameters: {
      oscWave: 1,
      oscDetune: 0.15,
      oscSub: 0.55,
      oscDrift: 0.06,
      fxChorus: 0.08,
      fxReverb: 0.06,
      filterCutoff: 0.32,
      filterPeak: 0.52,
      filterEnvMod: 0.72,
      ampDecay: 0.38,
      ampRelease: 0.12,
      ampMaster: 0.82,
    },
  },
  {
    name: "Bass2",
    parameters: {
      oscWave: 0,
      oscDetune: 0.22,
      oscSub: 0.68,
      oscDrift: 0.04,
      fxChorus: 0,
      fxReverb: 0.04,
      filterCutoff: 0.25,
      filterPeak: 0.64,
      filterEnvMod: 0.88,
      ampDecay: 0.32,
      ampRelease: 0.1,
      ampMaster: 0.84,
    },
  },
  {
    name: "Lead1",
    parameters: {
      oscWave: 0,
      oscDetune: 0.3,
      oscSub: 0.15,
      oscDrift: 0.12,
      fxChorus: 0.32,
      fxReverb: 0.22,
      filterCutoff: 0.62,
      filterPeak: 0.34,
      filterEnvMod: 0.48,
      ampDecay: 0.58,
      ampRelease: 0.34,
      ampMaster: 0.8,
    },
  },
  {
    name: "Lead2",
    parameters: {
      oscWave: 2,
      oscDetune: 0.26,
      oscSub: 0.08,
      oscDrift: 0.1,
      fxChorus: 0.42,
      fxReverb: 0.28,
      filterCutoff: 0.7,
      filterPeak: 0.2,
      filterEnvMod: 0.3,
      ampDecay: 0.66,
      ampRelease: 0.42,
      ampMaster: 0.78,
    },
  },
  {
    name: "Pad1",
    parameters: {
      oscWave: 3,
      oscDetune: 0.35,
      oscSub: 0.12,
      oscDrift: 0.2,
      fxChorus: 0.7,
      fxReverb: 0.68,
      filterCutoff: 0.54,
      filterPeak: 0.12,
      filterEnvMod: 0.16,
      ampDecay: 1,
      ampRelease: 0.75,
      ampMaster: 0.72,
    },
  },
  {
    name: "Pad2",
    parameters: {
      oscWave: 2,
      oscDetune: 0.4,
      oscSub: 0.18,
      oscDrift: 0.25,
      fxChorus: 0.86,
      fxReverb: 0.74,
      filterCutoff: 0.46,
      filterPeak: 0.24,
      filterEnvMod: 0.22,
      ampDecay: 1,
      ampRelease: 0.82,
      ampMaster: 0.68,
    },
  },
];
