import { SynthParameters } from "@/defs/definitions";

export const allPresets: Record<string, SynthParameters> = {
  Init: {
    oscWave: 0,
    oscDetune: 0,
    oscSub: 0,
    oscDrift: 0,
    filterCutoff: 1,
    filterPeak: 0,
    filterDecay: 0,
    ampDecay: 1,
    ampRelease: 0.1,
    fxChorus: 0,
    fxReverb: 0,
    patchVolume: 0.8,
  },
  Bass1: {
    oscWave: 1,
    oscDetune: 0,
    oscSub: 0.8,
    oscDrift: 0,
    filterCutoff: 0.3,
    filterPeak: 0.5,
    filterDecay: 0.6,
    ampDecay: 0.3,
    ampRelease: 0.1,
    fxChorus: 0,
    fxReverb: 0,
    patchVolume: 0.8,
  },
  Bass2: {
    oscWave: 0,
    oscDetune: 0.2,
    oscSub: 0.5,
    oscDrift: 0.1,
    filterCutoff: 0.4,
    filterPeak: 0.3,
    filterDecay: 0.4,
    ampDecay: 0.4,
    ampRelease: 0.1,
    fxChorus: 0.2,
    fxReverb: 0.1,
    patchVolume: 0.8,
  },
  Lead1: {
    oscWave: 0,
    oscDetune: 0.3,
    oscSub: 0,
    oscDrift: 0.2,
    filterCutoff: 0.8,
    filterPeak: 0.4,
    filterDecay: 0.2,
    ampDecay: 1,
    ampRelease: 0.2,
    fxChorus: 0.1,
    fxReverb: 0.4,
    patchVolume: 0.8,
  },
  Lead2: {
    oscWave: 2,
    oscDetune: 0,
    oscSub: 0,
    oscDrift: 0.1,
    filterCutoff: 0.7,
    filterPeak: 0.6,
    filterDecay: 0.4,
    ampDecay: 0.5,
    ampRelease: 0.4,
    fxChorus: 0.3,
    fxReverb: 0.5,
    patchVolume: 0.8,
  },
  Pad1: {
    oscWave: 0,
    oscDetune: 0.8,
    oscSub: 0.2,
    oscDrift: 0.5,
    filterCutoff: 0.6,
    filterPeak: 0.2,
    filterDecay: 0.2,
    ampDecay: 1,
    ampRelease: 0.8,
    fxChorus: 0.8,
    fxReverb: 0.8,
    patchVolume: 0.8,
  },
  Pad2: {
    oscWave: 1,
    oscDetune: 0.5,
    oscSub: 0.4,
    oscDrift: 0.8,
    filterCutoff: 0.4,
    filterPeak: 0.1,
    filterDecay: 0.2,
    ampDecay: 1,
    ampRelease: 0.9,
    fxChorus: 0.5,
    fxReverb: 0.9,
    patchVolume: 0.8,
  },
};
