export const uiColors = {
  // clPanelBody: "#ddd",
  // clPrimary: "#fff",
  clKnobTick: "#f80",
  // clText: "#666",
  // clSectionBg: "#fff",
  // clSectionHeaderBg: "#f80",
  // clSectionEdge: "#f80",
  // clControlBg: "#fff",
  // clControlEdge: "#ddd",
  // clTopBarBg: "#999",
  // clButtonBg: "#fff",
  clPageBg: "#ccc",
  clPageText: "#fff",
  clGridBg: "#222266",
  clNote: "#88aacc",
  clAccent: "#AA88CC",
  clGlide: "#CCAA88",
  clText: "#CCCCFF",
};
